### ISSUE TITLE
NPM role

### ISSUE THREAD

**Issue by louisameline** [vuex-cloud/rfcs#2]
I finally was able to accept the npm invitation, it was buggy, thank you. I have the 'member' role though, could you please turn it to owner as well? Thank you very much

**Comment by mesqueeb** [comment]
@louisameline Yes of course. I couldn't choose a status before you accepted. 😉 

I would require you to use 2FA please. I just can't sleep well otherwise. 😆 
I'd highly suggest the app called "authy" to set up 2FA. It's by far my favourite app of all apps lol.

Go ahead and close this issue when you have set it up.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/3253920/69683265-98845f80-10f7-11ea-81b3-214d2cab337b.png">

**Comment by louisameline** [comment]
Sure, sorry, done. I already use Google Authenticator though :)
